version: '3.8'

services:
  malla-web:
    # Use pre-built image by default, override with 'build: .' for development
    image: ${MALLA_IMAGE:-ghcr.io/zenitram/malla:latest}
    # Uncomment the following line for local development:
    # build: .

    # Choose between Flask dev server and Gunicorn
    # Default: Flask development server (malla-web)
    # Production: Gunicorn WSGI server (malla-web-gunicorn)
    command: ${MALLA_WEB_COMMAND:-/app/.venv/bin/malla-web}

    ports:
      - "${MALLA_WEB_PORT:-5008}:5008"
    environment:
      - MALLA_HOST=0.0.0.0
      - MALLA_PORT=5008
      - MALLA_DATABASE_FILE=/app/data/meshtastic_history.db
      - MALLA_NAME=${MALLA_NAME:-Malla}
      - MALLA_SECRET_KEY=${MALLA_SECRET_KEY:-dev-secret-key-change-in-production}
      - MALLA_DEBUG=${MALLA_DEBUG:-false}
    volumes:
      - malla_data:/app/data
      # Optional: mount your own config file (uncomment if you have one)
      # - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    depends_on:
      - malla-capture

  malla-capture:
    # Use pre-built image by default, override with 'build: .' for development
    image: ${MALLA_IMAGE:-ghcr.io/zenitram/malla:latest}
    # Uncomment the following line for local development:
    # build: .
    command: ["/app/.venv/bin/malla-capture"]
    environment:
      - MALLA_DATABASE_FILE=/app/data/meshtastic_history.db
      # MQTT Configuration - set these in your .env file
      - MALLA_MQTT_BROKER_ADDRESS=${MALLA_MQTT_BROKER_ADDRESS}
      - MALLA_MQTT_PORT=${MALLA_MQTT_PORT:-1883}
      - MALLA_MQTT_USERNAME=${MALLA_MQTT_USERNAME:-}
      - MALLA_MQTT_PASSWORD=${MALLA_MQTT_PASSWORD:-}
      - MALLA_MQTT_TOPIC_PREFIX=${MALLA_MQTT_TOPIC_PREFIX:-msh}
      - MALLA_MQTT_TOPIC_SUFFIX=${MALLA_MQTT_TOPIC_SUFFIX:-/+/+/+/#}
      - MALLA_DEFAULT_CHANNEL_KEY=${MALLA_DEFAULT_CHANNEL_KEY:-}
    volumes:
      - malla_data:/app/data
      # Optional: mount your own config file (uncomment if you have one)
      # - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped

volumes:
  malla_data:
